version: '3.8'
services:
  stats-server:
    build: stats/service
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - STATS_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_STATS_USER=postgres
      - POSTGRES_STATS_PASSWORD=postgres

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats_db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_EWM_USER=postgres
      - POSTGRES_EWM_PASSWORD=postgres
      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm